config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post 'checker', to: 'pages#checker'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @text = flash[:text]
    @palindromes = flash[:palindromes]
    @non_palindromes = flash[:non_palindromes]
  end

  def checker
    text = params[:text]
    palindromes, non_palindromes = find_palindromes(text)
    flash[:text] = text
    flash[:palindromes] = palindromes
    flash[:non_palindromes] = non_palindromes
    redirect_to root_path
  end

  private

  def find_palindromes(text)
    words = text.downcase.gsub(/[^a-z0-9\s]/i, '').split
    palindromes = []
    non_palindromes = []
    words.each do |word|
      if palindrome?(word)
        palindromes << word
      else
        non_palindromes << word
      end
    end
    [palindromes, non_palindromes]

  end

  def palindrome?(word)
    word == word.reverse
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Palindrome</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= javascript_importmap_tags %>
	</head>
	<body>
		<%= render 'shared/nav' %>
		<%= yield %>
	</body>
</html>

app/views/pages/home.html.erb
<!-- Header-->
<header class="bg-dark py-5">
	<div class="container px-5">
		<div class="row gx-5 justify-content-center">
			<div class="col-lg-6">
				<div class="text-center my-5">
					<h1 class="display-5 fw-bolder text-white mb-2">🔄 Palindrome Magic: Unveil the Hidden Palindromes! 🔄</h1>
					<p class="lead text-white-50 mb-4">Welcome to the Palindrome Magic Checker! Enter any sentence below, and we'll reveal all the palindromes hidden within. Whether it's a single word or a complex sentence, our magic checker will find it for you!</p>
					<div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
						<a class="btn btn-primary btn-lg px-4 me-sm-3" href="#checker">Get Started</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<!-- Pricing section-->
<section class="bg-light py-5 border-bottom" id="checker">
	<div class="container px-5 my-5">
		<div class="text-center mb-5">
			<h2 class="fw-bolder">The Palindrome Magic</h2>
		</div>
		<div class="row gx-5 justify-content-center">
			<!-- Pricing card free-->
			<div class="col-lg-6 ">
				<div class="card mb-5 mb-xl-0">
					<div class="card-body p-5">
						<div class="mb-3">
							<%= form_with url: checker_path, local: true do |form| %>
								<div class="mb-3">
									<%= form.label :text, "Enter a word or sentence", class: "mb-2" %>
									<%= form.text_area :text, class: "form-control", rows: 5 %>
								</div>
								<div>
									<%= form.submit "Check", class: "btn btn-primary" %>
								</div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
			<!-- Pricing card pro-->
			<div class="col-lg-6 ">
				<div class="card mb-5 mb-xl-0">
					<div class="card-body p-5">
						<% if @text.present? %>
							<h2>✨ Result ✨</h2>
							<% if @palindromes.any? %>
								<p>The following palindromes were found in your sentence:</p>
								<ul>
									<% @palindromes.each do |palindrome| %>
										<li><%= palindrome %></li>
									<% end %>
								</ul>
							<% else %>
								<p>No palindromes found in your sentence.</p>
							<% end %>
							<% if @non_palindromes.any? %>
								<hr>
								<p>The following words are not palindromes:</p>
								<ul>
									<% @non_palindromes.each do |non_palindrome| %>
										<li><%= non_palindrome %></li>
									<% end %>
								</ul>
							<% end %>
						<% else %>
							<div class="text-center">
								<%= image_tag("checker.jpeg", width: 400) %>
							</div>
							<div class="mt-2 justify-content-center text-center">
								This Palindrome Checker prints out the palindromes and the non palindromes 
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<%# <!-- Testimonials section-->
<section class="py-5 border-bottom">
	<div class="container px-5 my-5 px-5">
		<div class="text-center mb-5">
			<h2 class="fw-bolder">Customer testimonials</h2>
			<p class="lead mb-0">Our customers love working with us</p>
		</div>
		<div class="row gx-5 justify-content-center">
			<div class="col-lg-6">
				<!-- Testimonial 1-->
				<div class="card mb-4">
					<div class="card-body p-4">
						<div class="d-flex">
							<div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
							<div class="ms-4">
								<p class="mb-1">Thank you for putting together such a great product. We loved working with you and the whole team, and we will be recommending you to others!</p>
								<div class="small text-muted">- Client Name, Location</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Testimonial 2-->
				<div class="card">
					<div class="card-body p-4">
						<div class="d-flex">
							<div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
							<div class="ms-4">
								<p class="mb-1">The whole team was a huge help with putting things together for our company and brand. We will be hiring them again in the near future for additional work!</p>
								<div class="small text-muted">- Client Name, Location</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section> %>
<!-- Footer-->
<footer class="py-5 bg-dark">
	<div class="container px-5">
		<p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
	</div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
</body>
</html>

app/views/shared/_nav.html.erb
	<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container px-5">
		<a class="navbar-brand fw-bold" href="/">Palindrome Checker</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
				<li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Home</a></li>
				<li class="nav-item"><a class="nav-link" href="#checker">Checker</a></li>
				<li class="nav-item"><a class="nav-link" href="#!">Teams</a></li>
			</ul>
		</div>
	</div>
</nav>